stages:
  - build
  - deploy
  - pages

build:
  stage: build
  script:
    - npm install

deploy:
  stage: deploy
  script:
    - npm start # หรือคำสั่งอื่นๆ ที่คุณใช้เพื่อรันแอป
  only:
    - main # หรือชื่อ branch ที่คุณต้องการ deploy

pages:
  stage: pages
  script:
    - mkdir .public
    - cp -r * .public # คัดลอกไฟล์ทั้งหมดไปยังโฟลเดอร์ .public
  artifacts:
    paths:
      - .public
  only:
    - main # หรือชื่อ branch ที่คุณต้องการเผยแพร่
