stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install

deploy:
  stage: deploy
  script:
    - npm start # หรือคำสั่งอื่นๆ ที่คุณใช้เพื่อรันแอป
  only:
    - main # หรือชื่อ branch ที่คุณต้องการ deploy
